### ISSUE TITLE
-Dfml.coreMods.load=net.ccbluex.liquidbounce.injection.forge.MixinLoader running error

### ISSUE THREAD

**Issue by Matrix-CN** [WYSI-Foundation/LiquidBouncePlus#17]
using -Dfml.coreMods.load=net.ccbluex.liquidbounce.injection.forge.MixinLoader start vanilla client???

**Comment by Matrix-CN** [comment]
login account login server have crash 
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[LiquidBounce+.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.minecraftforge.fml.client.FMLClientHandler.connectToServer(FMLClientHandler.java:847) ~[FMLClientHandler.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146791_a(GuiMultiplayer.java:376) ~[azh.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146796_h(GuiMultiplayer.java:365) ~[azh.class:?]
	at net.minecraft.client.gui.ServerListEntryNormal.func_148278_a(ServerListEntryNormal.java:326) ~[azk.class:?]
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41) ~[awd.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_73864_a(GuiMultiplayer.java:412) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555) ~[axu.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146274_d(GuiMultiplayer.java:81) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524) ~[axu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) ~[ave.class:?]
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.thealtening.api.TheAltening
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[LiquidBounce+.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.minecraftforge.fml.client.FMLClientHandler.connectToServer(FMLClientHandler.java:847) ~[FMLClientHandler.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146791_a(GuiMultiplayer.java:376) ~[azh.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146796_h(GuiMultiplayer.java:365) ~[azh.class:?]
	at net.minecraft.client.gui.ServerListEntryNormal.func_148278_a(ServerListEntryNormal.java:326) ~[azk.class:?]
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41) ~[awd.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_73864_a(GuiMultiplayer.java:412) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555) ~[axu.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146274_d(GuiMultiplayer.java:81) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524) ~[axu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) ~[ave.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.thealtening.api.TheAltening
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[LiquidBounce+.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[LiquidBounce+.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.minecraftforge.fml.client.FMLClientHandler.connectToServer(FMLClientHandler.java:847) ~[FMLClientHandler.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146791_a(GuiMultiplayer.java:376) ~[azh.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146796_h(GuiMultiplayer.java:365) ~[azh.class:?]
	at net.minecraft.client.gui.ServerListEntryNormal.func_148278_a(ServerListEntryNormal.java:326) ~[azk.class:?]
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41) ~[awd.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_73864_a(GuiMultiplayer.java:412) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555) ~[axu.class:?]
	at net.minecraft.client.gui.GuiMultiplayer.func_146274_d(GuiMultiplayer.java:81) ~[azh.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524) ~[axu.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) ~[ave.class:?]
	... 9 more
[00:14:39] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  InputFix (【中文输入】InputFix-1.8.x-v2.jar)
  TransformerLoader (LiquidBounce+.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/3/21 12:14 AM
Description: Updating screen events

java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiDisconnected
	at net.minecraftforge.fml.client.FMLClientHandler.connectToServer(FMLClientHandler.java:847)
	at net.minecraft.client.gui.GuiMultiplayer.func_146791_a(GuiMultiplayer.java:376)
	at net.minecraft.client.gui.GuiMultiplayer.func_146796_h(GuiMultiplayer.java:365)
	at net.minecraft.client.gui.ServerListEntryNormal.func_148278_a(ServerListEntryNormal.java:326)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiMultiplayer.func_73864_a(GuiMultiplayer.java:412)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiMultiplayer.func_146274_d(GuiMultiplayer.java:81)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiDisconnected
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.thealtening.api.TheAltening
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.thealtening.api.TheAltening
	... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.client.FMLClientHandler.connectToServer(FMLClientHandler.java:847)
	at net.minecraft.client.gui.GuiMultiplayer.func_146791_a(GuiMultiplayer.java:376)
	at net.minecraft.client.gui.GuiMultiplayer.func_146796_h(GuiMultiplayer.java:365)
	at net.minecraft.client.gui.ServerListEntryNormal.func_148278_a(ServerListEntryNormal.java:326)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiMultiplayer.func_73864_a(GuiMultiplayer.java:412)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at net.minecraft.client.gui.GuiMultiplayer.func_146274_d(GuiMultiplayer.java:81)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMultiplayer
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1171800696 bytes (1117 MB) / 1460666368 bytes (1393 MB) up to 1717567488 bytes (1638 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx1638m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	InputFix{1.8.x-v2} [InputFix] (minecraft.jar) 
	Loaded coremods (and transformers): 
InputFix (【中文输入】InputFix-1.8.x-v2.jar)
  lain.mods.inputfix.InputFixTransformer
TransformerLoader (LiquidBounce+.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	Launched Version: pvpver
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.5161, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 材质包breeZe v2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
[00:14:39] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# D:\1.8\.minecraft\crash-reports\crash-2021-10-03_00.14.39-client.txt

**Comment by exit-scammed** [comment]
Did you build it yourself or what? As I can see in the log it couldn't find TheAltening classes.
I build my source every day and there's no error, that's might be your issue.
And I have no idea why did you put that JVM argument before running Forge. Try reinstalling Forge or remove the argument.
